<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => '2 Sum 2g Injection',
                'batch_no' => '016N028',
                'stage' => 'Production',
                'type' => 'Injection',
                'status' => 'pending',
                'line_clearance' => false,
                'review' => false,
                'confirmation' => false,
                'remarks' => null,
                'created_at' => now()->setTime(20, 38),
            ],
            [
                'name' => 'Neucef 500mg Capsule',
                'batch_no' => '285N029',
                'stage' => 'Daniyal / S.Sir',
                'type' => 'Capsule',
                'status' => 'pending',
                'line_clearance' => false,
                'review' => false,
                'confirmation' => false,
                'remarks' => null,
                'created_at' => now()->setTime(7, 40),
            ],
            [
                'name' => 'Nivador 250mg Injection',
                'batch_no' => '289N011',
                'stage' => 'On Process',
                'type' => 'Injection',
                'status' => 'pending',
                'line_clearance' => false,
                'review' => false,
                'confirmation' => false,
                'remarks' => null,
                'created_at' => now()->setTime(7, 39),
            ],
            [
                'name' => 'Nivador 250mg Injection',
                'batch_no' => '289N010',
                'stage' => 'S.Sir (Confirmation) and Ashir (Correction)',
                'type' => 'Injection',
                'status' => 'pending',
                'line_clearance' => false,
                'review' => false,
                'confirmation' => false,
                'remarks' => null,
                'created_at' => now()->setTime(7, 39),
            ],
            [
                'name' => '2 Sum 2g Injection',
                'batch_no' => '016N083',
                'stage' => 'On Process',
                'type' => 'Injection',
                'status' => 'pending',
                'line_clearance' => false,
                'review' => false,
                'confirmation' => false,
                'remarks' => null,
                'created_at' => now()->setTime(7, 37),
            ],
            [
                'name' => '2 Sum 2g Injection',
                'batch_no' => '016N082',
                'stage' => 'Transfer Note',
                'type' => 'Injection',
                'status' => 'pending',
                'line_clearance' => false,
                'review' => false,
                'confirmation' => false,
                'remarks' => null,
                'created_at' => now()->setTime(7, 37),
            ],
            [
                'name' => 'Abacus 200mg Tablet',
                'batch_no' => '004N008',
                'stage' => 'Dispensing',
                'type' => 'Tablet',
                'status' => 'pending',
                'line_clearance' => false,
                'review' => false,
                'confirmation' => false,
                'remarks' => null,
                'created_at' => now()->setTime(7, 36),
            ],
            [
                'name' => '2 Sum 500mg Injection',
                'batch_no' => '014N024',
                'stage' => 'Return',
                'type' => 'Injection',
                'status' => 'pending',
                'line_clearance' => false,
                'review' => false,
                'confirmation' => false,
                'remarks' => null,
                'created_at' => now()->setTime(7, 36),
            ],
            [
                'name' => '2 Sum 500mg Injection (PS)',
                'batch_no' => '014N023',
                'stage' => 'On Process',
                'type' => 'Injection',
                'status' => 'pending',
                'line_clearance' => false,
                'review' => false,
                'confirmation' => false,
                'remarks' => null,
                'created_at' => now()->setTime(7, 35),
            ],
            [
                'name' => '2 Sum 500mg Injection',
                'batch_no' => '014N022',
                'stage' => 'QA Sign',
                'type' => 'Injection',
                'status' => 'pending',
                'line_clearance' => false,
                'review' => false,
                'confirmation' => false,
                'remarks' => null,
                'created_at' => now()->setTime(7, 35),
            ],
            [
                'name' => '2 Sum 1g Injection',
                'batch_no' => '015N031',
                'stage' => 'QA Sign',
                'type' => 'Injection',
                'status' => 'pending',
                'line_clearance' => false,
                'review' => false,
                'confirmation' => false,
                'remarks' => null,
                'created_at' => now()->setTime(7, 34),
            ],
            [
                'name' => '2 Sum 1g Injection',
                'batch_no' => '015N030',
                'stage' => 'QA Sign',
                'type' => 'Injection',
                'status' => 'pending',
                'line_clearance' => false,
                'review' => false,
                'confirmation' => false,
                'remarks' => null,
                'created_at' => now()->setTime(7, 34),
            ],
            [
                'name' => 'Caricef 100mg/5ml Susp.',
                'batch_no' => '281N182',
                'stage' => 'On Process',
                'type' => 'Suspension',
                'status' => 'pending',
                'line_clearance' => false,
                'review' => false,
                'confirmation' => false,
                'remarks' => null,
                'created_at' => now()->setTime(7, 33),
            ],
            [
                'name' => 'Caricef 100mg/5ml Susp.',
                'batch_no' => '281N181',
                'stage' => 'On Process',
                'type' => 'Suspension',
                'status' => 'pending',
                'line_clearance' => false,
                'review' => false,
                'confirmation' => false,
                'remarks' => null,
                'created_at' => now()->setTime(7, 32),
            ],
            [
                'name' => 'Caricef 100mg/5ml Susp.',
                'batch_no' => '281N180',
                'stage' => 'On Process',
                'type' => 'Suspension',
                'status' => 'pending',
                'line_clearance' => false,
                'review' => false,
                'confirmation' => false,
                'remarks' => null,
                'created_at' => now()->setTime(7, 32),
            ],
            [
                'name' => 'Caricef 100mg/5ml Susp.',
                'batch_no' => '281N179',
                'stage' => 'Completed',
                'type' => 'Suspension',
                'status' => 'submitted',
                'line_clearance' => true,
                'review' => true,
                'confirmation' => true,
                'remarks' => null,
                'created_at' => now()->setTime(7, 30),
                'submission_date' => now()->toDateString(),
                'submission_time' => '07:30:00',
            ],
        ];

        foreach ($products as $product) {
            \App\Models\Product::create($product);
        }
    }
}
